---
- name: Converge
  hosts: all
  become: true
  vars:
    kubeadm_role: control_plane
    kubeadm_init_cluster: false  # Don't actually init the cluster in tests
  tasks:
    - name: Include kubeadm role
      include_role:
        name: kubeadm
      vars:
        kubeadm_version: ""  # Use latest for tests